### ISSUE TITLE
Test against sleef

### ISSUE THREAD

**Issue by gnzlbg** [burrbull/sleef-rs#1]
If you want to test this against sleef, let me know and I can try to set up the testing system using `sleef-sys`. I'm currently using `sleef-sys` in packed simd but would prefer to use a rust only library instead.

**Comment by burrbull** [comment]
I can not say how long it will take to fully port the library. Now only the simplest part is made.
But it would be nice to have a testing system.

**Comment by burrbull** [comment]
I made alpha version of Steel v3.3.1 port using packed_simd.
Some function are still not optimized. And I'm sure this contains a lot of bugs.
So it's time to test it.

**Comment by gnzlbg** [comment]
What is `Steel v3.3.1` ? 

Note that `packed_simd` links against the sleef C library when the `sleef-sys` feature is enabled. Otherwise, the math operations are scalarized to `libm` calls, which might be more accurate than the `sleef` functions for some cases or produce different results in some platforms (where libm might be buggy). IEEE754 requires 0.5 ULP precision, but many (not all) sleef functions have 1.0 ULP precision.

**Comment by burrbull** [comment]
I wrote simple random tests to compare it against `libm` or system (with `std` feature) functions.
It allowed me to find a few errors in implementation of functions for f64x..
Also I actualized code base to be conformable with sleef master.
But I've tested it only on my 64bit linux system and I'm not sure how it will work on other systems with different target gates.
Please, @gnzlbg, say what are you think about this.

I splited implementation for different types into different modules.
One of questions is how should funtions for f32 like types to be named: `f32x2::u10::sin` or `f32x2::u10::sinf` like in `libm`?

**Comment by gnzlbg** [comment]
I'll check it out this week. For `f32` scalars you can check the results for all inputs in a reasonable amount of time with `--release`. Why isn't it compared against `sleef` implementation as well ? (shouldn't be too hard using `sleef-sys` or a similar wrapper).

**Comment by gnzlbg** [comment]
> I splited implementation for different types into different modules.

I think that internally you should organize things in such a way that keep things sane. I would expect that to be `<type>::<op>::<precision_fn>` or just `<op>::<ty_precision_fn>`, so `f32x2::sin::u10` or `sin:::f32x2_u10` or similar, because I expect that you want to keep the different precision implementations of an operation close to each other. 

For the library Rust API, I'd just keep it as simple as possible, e.g., simple Rust functions whose name expresses what they do. I find `sleef` names clear, but `libm` names are clear to. People won't probably use this library directly, but will use it through wrappers. Chances are that those wrappers might want to alternatively interface with `libm` or `sleef-sys` directly as well, so keeping names similar to those makes those wrappers simpler to write / maintain. 

I expect that, as this gets completed (and we merge Rust SIMD FFI support), this library will contain `extern "C"` functions that expose the SLEEF operations, so that the library can be called from C.

**Comment by burrbull** [comment]
I can reexport them as `f32x2::sin::u10`
What about `f32x2::sinf_u10` ?

**Comment by burrbull** [comment]
> I'll check it out this week. For `f32` scalars you can check the results for all inputs in a reasonable amount of time with `--release`. Why isn't it compared against `sleef` implementation as well ? (shouldn't be too hard using `sleef-sys` or a similar wrapper).

I can try, but it compiles veeery slow.

**Comment by gnzlbg** [comment]
> I can try, but it compiles veeery slow.

We can fix that. Ideally, we would drop rust-bindgen, and just manually add all declarations. I can do that I think.

**Comment by burrbull** [comment]
Is [this](https://github.com/burrbull/sleef-rs/commit/2ada224b06c2553c2ed2a5bb7467dc7da1afe779) better?

**Comment by gnzlbg** [comment]
That's good!
