### ISSUE TITLE
Is this library still being developed/will it get released to crates.io?

### ISSUE THREAD

**Issue by zachmatson** [burrbull/sleef-rs#7]
Having something like this in pure Rust would be very useful and a lot simpler than bringing the C Sleef library into Rust projects. It seems like a good deal of effort has been put into this but it hasn't had commits in a while, is this still something that will be released eventually, or if not are the developers aware of any other pure-Rust vectorized math library?

I don't want this to sound like a demand on the maintainers/developers of this crate, I was just curious.

**Comment by lfnoise** [comment]
I am also very interested in this library. The author's stated location is "Ukraine, Donets'k", so I would assume that they have experienced significant disruption in life to say the least. (But apparently are still making github commits.)

**Comment by burrbull** [comment]
I've missed this issue. 

The main reason I abandoned this crate is `packed-simd` still nightly only.
Also it is needed to review changes in `sleef` were made since last update (mostly fast low accuracy versions of functions as I remember).
It should be not hard to update.
And last statement is also actual.

**Comment by lfnoise** [comment]
Thank you. Best wishes to you in this time.

**Comment by burrbull** [comment]
@zachmatson @lfnoise @gnzlbg @shibatch I resurrected the project. Now it compiles on last `packed_simd`.

Testing system was rewritten with `rug::Float`'s. It passes most of tests, but not all. So help is needed. (https://github.com/burrbull/sleef-rs/runs/7610630457?check_suite_focus=true)
Also need to review changes in `Sleef` of last 3 years.

~~Upd. Several bugs & tests are fixed (not all yet): https://github.com/burrbull/sleef-rs/runs/7624784445?check_suite_focus=true~~
Upd 2. Tests passed. Docs added.

**Comment by burrbull** [comment]
cc @calebzulawski @workingjubilee

**Comment by burrbull** [comment]
Now on crates.io
https://docs.rs/sleef/0.1.0/sleef/

**Comment by zachmatson** [comment]
Amazing, thank you! This is a great crate to have available

**Comment by burrbull** [comment]
ported on `core::simd`, several bugs fixed
